Task 70 - taking screenshot
pavel-kostoglod/automation_training_selenuim pull request #4
Opened 2022-04-26 11:27 UTC by pavel-kostoglod

2022-04-29 07:26 UTC, KirKarpov requested changes

2022-04-29 07:26 UTC, KirKarpov commented on src/test/java/task_60_1/LoginTests.java
> +        }
It is utility method. It will be good to move it to some kind of utility class. It will allow you to reuse method

2022-05-30 08:58 UTC, KirKarpov requested changes

2022-05-30 08:58 UTC, KirKarpov commented on src/test/java/task_60_2/LoginTests.java
> +    void verifyLoginAndLogout() {
According to  the task it should be 2 tests

2022-05-30 08:58 UTC, KirKarpov commented on src/test/java/task_60_2/HomePage.java
> +package task_60_2;
Please create page and test packages. After that split classes

2022-06-15 21:29 UTC, pavel-kostoglod commented
Will commit the changes with the next task

2022-06-29 19:31 UTC, merged